### ISSUE TITLE
vue-tsc errors when importing components

### ISSUE THREAD

**Issue by devtobi** [it-at-m/muc-patternlab-vue#199]
**Describe the bug**
In my project (see https://github.com/it-at-m/refarch-templates/tree/feat/5-add-webcomponent-template) I get errors when trying to import a Web Component in a TypeScript based Vue SFC.
The error is reported by the tool `vue-tsc`.

I am not 100% sure if its a issue by muc-patternlab-vue or my specific setup of dependencies and configuration files used in the project

**To Reproduce**
1. Checkout https://github.com/it-at-m/refarch-templates/tree/feat/5-add-webcomponent-template
2. Open `refarch-hello-world-webcomponent.ce.vue`
3. Error appears in IDE and when executing vue-tsc

**Expected behavior**

**Screenshots**
![grafik](https://github.com/user-attachments/assets/6c7fd364-0e77-41cb-b1fa-32089b571c30)

**Additional context**
I am using the following dependencies. This might help in replicating the issue:
```
  "dependencies": {
    "@muenchen/muc-patternlab-vue": "1.13.0",
    "@vueuse/core": "^10.9.0",
    "vue": "^3.4.21"
  },
  "devDependencies": {
    "@muenchen/prettier-codeformat": "^1.0.1",
    "@rushstack/eslint-patch": "^1.10.2",
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.0.0",
    "@typescript-eslint/eslint-plugin": "^7.6.0",
    "@typescript-eslint/parser": "^7.6.0",
    "@unplugin-vue-ce/sub-style": "^1.0.0-beta.21",
    "@vitejs/plugin-vue": "^5.0.4",
    "@vue/eslint-config-prettier": "^9.0.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "@vue/test-utils": "^2.4.1",
    "@vue/tsconfig": "^0.5.1",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.24.1",
    "prettier": "^3.2.5",
    "typescript": "^5.4.5",
    "vite": "^5.2.8",
    "vitest": "^2.0.0",
    "vite-plugin-css-injected-by-js": "^3.5.0",
    "vue-tsc": "^2.0.12"
  }
  ```

I got Node `20.14.0` installed on my machine.

**Comment by FabianWilms** [comment]
There seems to have been a change in how the library was getting published. Previously it only uploaded the contents of the `dist`-Folder to npm, but currently it uploads everything.

So at the moment a quick fix would be to change the import-Statement from e.g.

```js
import {MucCard} from "@muenchen/muc-patternlab-vue";
```

to

```js
import {MucCard} from "@muenchen/muc-patternlab-vue/dist";
```

I'm now trying to find out why it changed the publishing behaviour.

**Comment by FabianWilms** [comment]
This should be fixed with https://github.com/it-at-m/muc-patternlab-vue/commit/58b7cd367fd33c47c6b7ce5189bebad3e72be9c9

Can you please try out beta-Version `1.13.0-beta.8` and report back if this fixes your problem?

**Comment by devtobi** [comment]
Unfortunately it still does not work with the version above. I still get the same exact error
```
src/refarch-hello-world-webcomponent.ce.vue:19:28 - error TS2307: Cannot find module '@muenchen/muc-patternlab-vue' or its corresponding type declarations.

19 import { MucCallout } from "@muenchen/muc-patternlab-vue";
```

by vue-tsc and the IDE still underlines the import as invalid.

**Comment by devtobi** [comment]
It works now. :) Thank you very much. We can close this issue. ;)
